task:
  name: HumanoidAMP
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    envSpacing: 5
    episodeLength: 1000
    cameraFollow: true
    enableDebugVis: false
    pdControl: true
    powerScale: 1.0
    controlFrequencyInv: 2
    stateInit: Random
    hybridInitProb: 0.5
    numAMPObsSteps: 2
    localRootObs: false
    contactBodies:
    - right_foot
    - left_foot
    - right_hand
    - left_hand
    terminationHeight: 0.5
    enableEarlyTermination: true
    motion_file: amp_humanoid_run.npy
    asset:
      assetFileName: mjcf/amp_humanoid.xml
    plane:
      staticFriction: 1.0
      dynamicFriction: 1.0
      restitution: 0.0
    TLObs: false
    MAObs: false
    MFObs: true
    MRObs: false
    useFatigue: false
    fatigueF: 1.0
    fatigueR: 0.1
    fatigue_r: 1.0
    useTorqueCoeff: false
    useStiffnessCoeff: true
    useDampingCoeff: false
    randomizeFatigueProb: 1
    randomizeEveryStep: true
    customPD: false
    zeroStiffnessDamping: false
    effortLimiting: false
    strength: male
    regularize: None
    useMotionTLDenom: false
    TargetObs: true
  sim:
    dt: 0.0166
    substeps: 2
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 4
      num_velocity_iterations: 0
      contact_offset: 0.02
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 10.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 8388608
      num_subscenes: ${....num_subscenes}
      contact_collection: 1
  task:
    randomize: false
    randomization_params:
      frequency: 600
      observations:
        range:
        - 0
        - 0.002
        operation: additive
        distribution: gaussian
      actions:
        range:
        - 0.0
        - 0.02
        operation: additive
        distribution: gaussian
      sim_params:
        gravity:
          range:
          - 0
          - 0.4
          operation: additive
          distribution: gaussian
          schedule: linear
          schedule_steps: 3000
      actor_params:
        humanoid:
          color: true
          rigid_body_properties:
            mass:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              setup_only: true
              schedule: linear
              schedule_steps: 3000
          rigid_shape_properties:
            friction:
              num_buckets: 500
              range:
              - 0.7
              - 1.3
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            restitution:
              range:
              - 0.0
              - 0.7
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
          dof_properties:
            damping:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            stiffness:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            lower:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
              schedule: linear
              schedule_steps: 3000
            upper:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
              schedule: linear
              schedule_steps: 3000
train:
  params:
    seed: ${...seed}
    algo:
      name: amp_continuous
    model:
      name: continuous_amp
    network:
      name: amp
      separate: true
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: -2.9
          fixed_sigma: true
          learn_sigma: false
      mlp:
        units:
        - 1024
        - 512
        activation: relu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
      disc:
        units:
        - 1024
        - 512
        activation: relu
        initializer:
          name: default
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:HumanoidAMP,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      ppo: true
      multi_gpu: false
      mixed_precision: false
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 1
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 5.0e-05
      lr_schedule: constant
      kl_threshold: 0.008
      score_to_win: 20000
      max_epochs: ${resolve_default:5000,${....max_iterations}}
      save_best_after: 100
      save_frequency: 500
      print_stats: true
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: false
      e_clip: 0.2
      horizon_length: 16
      minibatch_size: 32768
      mini_epochs: 6
      critic_coef: 5
      clip_value: false
      seq_len: 4
      bounds_loss_coef: 10
      amp_obs_demo_buffer_size: 200000
      amp_replay_buffer_size: 1000000
      amp_replay_keep_prob: 0.01
      amp_batch_size: 512
      amp_minibatch_size: 4096
      disc_coef: 5
      disc_logit_reg: 0.05
      disc_grad_penalty: 5.0
      disc_reward_scale: 2
      disc_weight_decay: 0.0001
      normalize_amp_input: true
      task_reward_w: 1.0
      disc_reward_w: 1.0
      regterm: additive
task_name: ${task.name}
experiment: experiment2
num_envs: 64
seed: 537
torch_deterministic: false
max_iterations: 2000
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: true
checkpoint: /home/noshaba/fatigue/runs/537_goal/experiment2/nn/experiment2.pth
multi_gpu: false
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: isaacgymenvs
capture_video: false
capture_video_freq: 1464
capture_video_len: 100
force_render: true
headless: false
